#!/usr/bin/env python

import os
import sys

import argparse
from scipy import signal
from matplotlib import pyplot as plt

import numpy as np
from scipy import signal
import psana 


ERASE_LINE = '\x1b[1A\x1b[2K'
DARK = np.load('/reg/neh/home2/tjlane/run139.npy')


parser = argparse.ArgumentParser(description='Average some runs from the current experiment')
parser.add_argument(
    '-r', '--run',
    type=int,
    help='run to process',
    required=True,
    default=-1)
args = parser.parse_args()

aqiris_src     = psana.Source('DetInfo(CxiEndstation.0:Acqiris.0)')
cspad_ds1_src  = psana.Source('DetInfo(CxiDs1.0:Cspad.0)')
evr_src        = psana.Source('DetInfo(NoDetector.0:Evr.0)')
dg2_src        = psana.Source('DetInfo(CxiDg2.0:Ipimb.0)')

if args.run == -1:
    print 'running from shmem'
    run_txt = 'LIVE'
    ds = psana.DataSource('shmem=CXI.0:stop=no')
else:
    print "\nReading run #: %d" % args.run
    run_txt = str(args.run)
    ds = psana.DataSource('exp=cxif7214:run=%d' % int(args.run) )
epics = ds.env().epicsStore()


shot_index = 0
plt.ion()
plt.figure()
plt.suptitle('%s Aqiris Channel 6' % run_txt)

for evt in ds.events():

    # --> EVR CODES
    EVR_code = evt.get(psana.EvrData.DataV3, evr_src)
    if EVR_code is None:
        print 'Error, EVR code is `None`'
        continue

    fifos = evt.get(psana.EvrData.DataV3, psana.Source('DetInfo(NoDetector.0:Evr.0)')).fifoEvents()
    shot_evrs = [e.eventCode() for e in fifos]

    # --> Acqiris
    aqiris = evt.get(psana.Acqiris.DataDescV1, aqiris_src)
    aqiris_wvfm = aqiris.data(5).waveforms().flatten() # channel 6 waveform

    plt.cla()
    plt.plot( signal.medfilt(aqiris_wvfm, 5) )
    plt.draw()

    shot_index += 1



