#!/usr/bin/env python

"""
TJL Oct 22, 2014
"""

import argparse
import numpy as np

from minitti.libminitti import *
from minitti.shot import Event

from pypad import psana as psutil
from pypad import cspad

import psana
from trapdoor import core


# ---------------------------
# manually set parameters
n_q_bins          = 101
update_frequency  = 100

ds1_offset    = 500.0 # mm 
ds2_offset    = 2800.0 # mm
energy_offset = 0.0 # eV
# ---------------------------


class MinittiAnalyzer(core.MapReducer):
    
    def __init__(self, **kwargs):
        
        self.args = self.parse_args()
        self.zmq_initialized = False

        super(MinittiAnalyzeri, self).__init__(self.map, self.reduce, self.action_func, **kwargs)
        
        ds = psana.DataSource(self._source_string())
        
        self.epics = ds.env().epicsStore()
        self.calib = ds.env().calibStore()
        ds.events().next()
        
        self.energy = self.epics.value('SIOC:SYS0:ML00:AO627') + energy_offset
        self.ds1_dist = self.epics.value('CXI:DS1:MMS:06.RBV') + ds1_offset
        self.ds2_dist = self.epics.value('CXI:DS2:MMS:07.RBV') + ds2_offset
        
        # geometries are (3, 32, 185, 388)
        ds1_cspad = cspad.CSPad.load('/reg/d/psdm/cxi/cxif7214/res/geometries/v0/default_5mm_dilation.cspad')
        ds2_cspad = cspad.CSPad.load('/reg/d/psdm/cxi/cxif7214/res/geometries/v0/default_5mm_dilation.cspad')

        ds1_geom = recpolar_convert( ds1_cspad.to_thor(self.energy, self.ds1_dist).recpolar )
        ds2_geom = recpolar_convert( ds1_cspad.to_thor(self.energy, self.ds2_dist).recpolar )

        # masks are (32, 185, 388)
        ds1_mask = np.load('/reg/d/psdm/cxi/cxif7214/res/masks/v0/ds1.npy')
        ds2_mask = np.load('/reg/d/psdm/cxi/cxif7214/res/masks/v0/ds2.npy')
        
        self.ds1_ra = RadialAverager(ds1_geom[0,:,:,:], ds1_mask, n_bins=n_q_bins)
        self.ds2_ra = RadialAverager(ds2_geom[0,:,:,:], ds2_mask, n_bins=n_q_bins)

        self.agg = EventAggregator()
        self.tt_hist = TTHistogram(ds1_geom, ds2_geom, bin_width=5.0)
        
        return
    
        
    def parse_args(self):
        parser = argparse.ArgumentParser(description='Psana plot server application')
        parser.add_argument(
            '-r',
            '--run',
            type=int,
            default=-1,
            help='Which run to analyze, -1 for live stream',
        )
        parser.add_argument(
            '-p',
            '--port',
            metavar='PORT',
            type=int,
            default=5556,
            help='the tcp port to use on the server'
        )
        parser.add_argument(
            '-c',
            '--client',
            action='store_true',
            help='open a corresponding client that will show plots'
        )

        if args.source == -1:
            self._source = 'cxishmem'
        else:
            self._source = 'exp=cxif7214:run=%d:idx' % parser.parse_args().run
 
        return parser.parse_args()
    
        
    def init_zmq(self):
        self.zmq_initialized = True
        context = zmq.Context()
        socket = context.socket(zmq.PUB)
        socket.setsockopt(zmq.SNDHWM, 10)
        socket.bind("tcp://*:%d" % self.args.port)
        print "Broadcasting via ZMQ on port: %d" % self.args.port
        self.socket = socket
        return
    
        
    def data_source(self):
        s = 'exp=cxif7214:run=%d' % self.args.run
        return s
    
        
    def map(self, evt):
        return Event(evt, self.epics, 
                     ds1_offset, ds2_offset,
                     energy_offset, corrected=False)
    
        
    def reduce(self, evt, old=None):
        
        cspad_intensities = np.array((evt.ds1_intensities,
                                      evt.ds2_intensities))
       
        self.agg.add_shot(cspad_intensities,
                          evt.pump_laser_status,
                          0)
                 
        self.tt_hist.add_shot(evt.pumpprobe_delay_fs,
                              evt.pump_laser_status,
                              evt.polarization_status,
                              cspad_intensities)
        
        return 0
    
        
    def action(self, placeholder=None):

        if not self.zmq_initialized:
            self.init_zmq()
        
        q = np.concatenate([self.ds2_ra.bin_centers,
                            self.ds1_ra.bin_centers])

        ds1_on = self.ds1_ra(self.agg.laseron_avg[0,:,:,:])
        ds2_on = self.ds2_ra(self.agg.laseron_avg[1,:,:,:])
        on_avg = np.concatenate([ds2_on, ds1_on])

        ds1_off = self.ds1_ra(self.agg.laseroff_avg[0,:,:,:])
        ds2_off = self.ds2_ra(self.agg.laseroff_avg[1,:,:,:])
        off_avg = np.concatenate([ds2_off, ds1_off])

        diff = on_avg - off_avg
        percent = diff / off_avg

        transmission = {
                        'title'         : 'RUN %d | x SHOTS PROCESSED' % (self.args.run,),
                        'q_values'      : q,
                        'laser_on_avg'  : on_avg,
                        'laser_off_avg' : off_avg,
                        'diff'          : diff,
                        'percent_diff'  : percent
                       }
        
        self.socket.send("data", zmq.SNDMORE)
        self.socket.send_pyobj(transmission)
        
        return


    def finish():
        print 'Done processing run.'

        fn = '/reg/d/psdm/cxi/cxif7214/scratch/timehists/run%d.h5' % args.run
        if os.path.exists(fn):
            os.remove(fn)
            print 'Removing old file: %s' % fn
        
        tt_hist.save(fn)
        print 'Wrote: %s' % fn
        
        return
    

if __name__ == '__main__':
    m = MinittiAnalyzer(config_file='/reg/d/psdm/cxi/cxif7214/res/cfg/cxif7214.cfg')
    m.start(verbose=True)
    
    
    
