#!/usr/bin/env python

import sys
import numpy as np
from matplotlib import pyplot as plt

from pypad import cspad
from pypad import plot as padplot
from pypad.read import enforce_raw_img_shape as eris
from minitti.libminitti import RadialAverager

print 'usage: ./min-compare-averages <run1> <run2>'
print sys.argv

run1 = int(sys.argv[1])
run2 = int(sys.argv[2])

average_file_path = '/reg/d/psdm/cxi/cxif7214/scratch/averages/run%s_ds1_average.npy'
run1_average = np.load(average_file_path % run1)
run2_average = np.load(average_file_path % run2)
print 'loaded runs: %d, %d' % (run1, run2)

geom = cspad.CSPad.load('/reg/d/psdm/cxi/cxif7214/scratch/averages/approx.cspad')
dtc = geom.to_thor(9500, 108)

ra = RadialAverager(dtc.recpolar[:,0], np.ones((32 * 185 * 388)))

Iq1 = ra( eris(run1_average).flatten() )
Iq2 = ra( eris(run2_average).flatten() )

plt.figure(figsize=(12,6))
plt.suptitle('Run %d minus Run %d' % (run1, run2))

ax = plt.subplot(121)
padplot.imshow_cspad( geom( eris(run1_average - run2_average) ), ax=ax, vmax=5 )
#plt.imshow( geom( eris(run1_average - run2_average) ) )

ax = plt.subplot(122)
plt.plot(ra.bin_centers, Iq1 - Iq2, lw=2)
plt.xlabel(r'q $\AA^{-1}$')
plt.ylabel('Intensity Difference (ADU)')

plt.show()


