#!/usr/bin/env python

import sys
import numpy as np
from matplotlib import pyplot as plt

from pypad import cspad
from pypad import plot as padplot
from pypad.read import enforce_raw_img_shape as eris
from minitti.libminitti import RadialAverager

print 'usage: ./show-averages <run> <detector>'
print 'default detector is front'
print sys.argv

run = int(sys.argv[1])
#det = sys.argv[2]
det=''

#if det in ['1', 'ds1', 'front']:
#    det = 'ds1'
#elif det in ['2', 'ds2', 'back']:
#    det = 'ds2'
#else:
#    print 'WAAAAAA -- dont understand detector: %s' % det
#    print 'use "front" or "back" for detector'

average_file_path = '/reg/d/psdm/cxi/cxif7214/scratch/averages/run%d_%s_average.npy'
run_average_front = np.load(average_file_path % (run, 'ds1'))
run_average_back = np.load(average_file_path % (run, 'ds2'))
print 'loaded runs: %d, camera: %s' % (run, det)

geom = cspad.CSPad.load('/reg/d/psdm/cxi/cxif7214/scratch/averages/approx.cspad')
#dtc = geom.to_thor(9500, 108)
#q_values = dtc.recpolar[:,0]

q_values = np.load('/reg/d/psdm/cxi/cxif7214/scratch/averages/approx_qs.npy')
mask = np.ones((32 * 185 * 388))

ra = RadialAverager(q_values, mask)

Iq_front = ra( eris(run_average_front).flatten() )
Iq_back = ra( eris(run_average_back).flatten() )

plt.figure(figsize=(12,6))
plt.suptitle('Run %d' % (run))

ax = plt.subplot(221)
ax.set_title('front')
padplot.imshow_cspad( geom( eris(run_average_front) ), ax=ax, vmax=0.05, scrollable=True )
#plt.imshow( geom( eris(run_average_front) ) )

ax = plt.subplot(222)
plt.plot(ra.bin_centers, Iq_front, lw=2)
plt.xlabel(r'q $\AA^{-1}$')
plt.ylabel('Intensity Difference (ADU)')

ax = plt.subplot(223)
ax.set_title('back')
padplot.imshow_cspad( geom( eris(run_average_back) ), ax=ax, vmax=0.05, scrollable=True )
#plt.imshow( geom( eris(run_average_back) ) )

ax = plt.subplot(224)
plt.plot(ra.bin_centers, Iq_back, lw=2)
plt.xlabel(r'q $\AA^{-1}$')
plt.ylabel('Intensity Difference (ADU)')

plt.show()


